apiVersion: v1
kind: Service
metadata:
  name: {{ include "rybbit.client.fullname" . }}
  labels:
    {{- include "rybbit.client.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rybbit.client.selectorLabels" . | nindent 4 }}
