apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rybbit.postgresql.pvcName" . }}
  labels:
    {{- include "rybbit.postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  