apiVersion: v1
kind: Service
metadata:
  name: {{ include "rybbit.postgresql.fullname" . }}
  labels:
    {{- include "rybbit.postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rybbit.postgresql.selectorLabels" . | nindent 4 }}
